export const FETCH_ASSIGNMENT_REQUEST = 'FETCH_ASSIGNMENT_DATA';
export const FETCH_ASSIGNMENT_SUCCESS = 'FETCH_ASSIGNMENT_SUCCESS';
export const FETCH_ASSIGNMENT_FAILURE = 'FETCH_ASSIGNMENT_FAILURE';
